New way to define attribute accessors and mutators in Laravel 8.77:
LaravelDaily/laravel-tips pull request #56
Opened 2022-01-04 07:54 UTC by TechyMS

2022-01-04 08:24 UTC, kang8 requested changes

2022-01-04 08:24 UTC, kang8 commented on README.md
> +    return strtolower($value);
It is `strtoupper($value)`?

2022-01-05 06:06 UTC, PovilasKorop commented
@TechyMS we released a new set of tips with another Pull Request, so now there's a conflict. Could you resolve the conflict, and fix the `strtoupper`, and then I will merge.

2022-01-05 09:18 UTC, TechyMS commented
Okay

2022-01-05 09:39 UTC, PovilasKorop commented
@TechyMS also, I think this tip is not in "Random" but should be in "Eloquent" section. Please move there, and also increase the number of tips - both in Eloquent section and in overall number.

2022-01-05 09:40 UTC, TechyMS commented
Sure

2022-01-05 09:47 UTC, TechyMS commented
is it ok now?

2022-01-05 11:05 UTC, merged

2022-01-05 11:05 UTC, PovilasKorop commented
@TechyMS almost, just need to change one number, I will do it in Master. Thanks for the contribution!